CREATE TABLE shop (
	BUSINESS_NUMBER		VARCHAR(13) 	PRIMARY KEY,
	SHOP_NAME 			VARCHAR(50) 	NOT NULL,
	SHOP_TEL			VARCHAR(12)		NOT NULL,
	SHOP_ADDRESS		VARCHAR(50)		NOT NULL,
	SHOP_HOURS			VARCHAR(11)		NOT NULL,
	SHOP_IMG			VARCHAR(10)		NOT NULL DEFAULT 'default'
);

CREATE TABLE menu (
	BUSINESS_NUMBER		VARCHAR(13) 	NOT NULL,
	SHOP_MENU_NAME		VARCHAR(20)		NOT NULL DEFAULT '-',
	SHOP_MENU_INTRO		VARCHAR(30)		NOT NULL DEFAULT '-',
	SHOP_MENU_PRICE		INT(6)			NOT NULL DEFAULT 0,
	SHOP_MENU_IMG		VARCHAR(10)		NOT NULL DEFAULT 'default',
	CONSTRAINT Shop_Name_FK
	FOREIGN KEY(BUSINESS_NUMBER) REFERENCES shop(BUSINESS_NUMBER)
);

DELETE FROM SHOP;
DELETE FROM MENU;

SELECT * FROM SHOP;
SELECT * FROM MENU;

DROP TABLE shop;
DROP TABLE menu;
